### PR TITLE
Johnathan/camera catchup_gameover threshhold_boundaries

### PR DESCRIPTION
**Pull request by JohnathanGlasgow**
- [x] Camera Catchup
- [x] Gameover Threshhold
- [x] Boundary Tiles

## Camera Catchup
NOTE: Liam and I accidentally implemented camera catchup concurrently.
In Liam's implementation, the viewport is used to determine player has entered the speedup area. This is good because it is a relatively cheap calculation compared to the collider I am currently using. The speed then accelerates to the catchup speed. When the player leaves the speed reverts to a hardcoded value matching the initial speed.

I initially used the viewport also, but I did not like the way it would speed up if I moved laterally. That is why I changed to a collider to trigger the speed increase. This way the trigger area is parallel to the rows and can't be triggered with lateral movement. But it's also less efficient.
My implementation also stores the speed before the catchup is started, so the speed can be incremented.
After seeing Liam's branch, I copied the acceleration idea, and added deceleration as well.

## Gameover Threshold
I'm using a collider for the Gameover trigger area. Currently this opens a placeholder Gameover dialog asking player to play again or quit.
I did actually end up tilting this to be parallel with the viewport rather than the grid, so using inViewport could be cheaper for this. Although using the collider makes it easy to move and test.
On reset, the tile map is regenerated and the player is respawned. Speed is set to its initial value.

## Fence Tiles
The fence tiles are determined by the boundaryLeft and boundaryRight fields in the DifficultyProfile. In the TileData class it can be specified if these occur only inside or outside (leave both unchecked for a tile to occur inside and outside the fence).
The fence works by storing a reference to the fence prefab in the tiles that might contain a fence, essentially the row tiles like water and road as well as the default tiles. This way they can have their own fence model, ie a gate for the road model. The fence is then instantiated from the TileController where it is given the correct orientation (TileControllerBuildFence()).

### CODE REVIEW

**Review by DevonHenderson — CHANGES_REQUESTED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the the user’s requirements and properly address the issue?_  

**Camera Catchup:**
 - Almost, I have noticed that while the player is still onscreen it triggers the game over panel. I think it would probably be best to have this panel only show if the player has completely left the viewable play area at the bottom.

https://github.com/LiamMcKenzie/ScaredKrow/assets/90590089/42d9860c-fe5d-436f-a25f-a187aa3d1132

 - After testing moving the "GameoverTriggerArea" I found the following values to be a bit more forgiving for waiting for the player to exit the view area (X: -3.8, Y: 0.003, Z: 6.23) before triggering the gameover

https://github.com/LiamMcKenzie/ScaredKrow/assets/90590089/9b57a635-1a45-43ae-bd77-1fff75ebcbfd

 - With the max speed of 4 I found it somewhat difficult to keep up with the camera unless I was spamming UP as fast as possible. Will be something we find a balance for once everything is merged (much like how fast the camera speeds up over time)


**Gameover:**
 - Works for the purpose of merging. Will be good to connect this to the players health value when that is implemented


**Boundary Tiles:**
 - This looks fantastic. Having the outer area darker than the play area, as well as have different trees, really helps seperate the playable and unplayable game space. The fences integrate extremely well with the border/rivers/paths and I see no issues here.

## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Really good here. Everything is seperated logically and great comments throughout

_Any repetitive code that could be refactored? (DRY)_  

 - None

## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Everything functions correctly without issues
 - Staying in the CatchupArea stops the default speed from increasing. Assuming this is an aspect of gameplay where it is riskier to stay near the top of the screen but it makes it easier if you have to slow down at any point (vs the speed still increasing to the maximum while the player is in the catchup area.)


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No issues here. Having a target framerate in the GameManager will help ensure it is playable on a range of devices.


# Final Comments

 - Just requesting the slight change of moving back the GameoverTriggerArea slightly so the player has to leave the viewport before losing.

***

**Comment by JohnathanGlasgow** [comment]
I put the game over trigger on screen because that's where it is in crossy road. But I've moved it anyway. 
IMG_6CBC695E8CC8-1

The base speed not increasing during catchup was an oversight. I've refactored the speed code so the actual speed is set to either the base speed (which continues to increment independently) or accelerates/decelerates to the catchup speed depending if catchup is initiated. The base speed continues to increment to the maximum *base* speed. Whereas the catchup speed is effectively the maximum *actual* speed.
The player shouldn't be able to stay in the cathchup area so I've tweaked the settings to kick them out faster. But we can continue to adjust this as needed.

**Comment by JohnathanGlasgow** [comment]
I've also moved the tileOnlyOccursInsideBoundary/tileOnlyOccursOutsideBoundary flags from the TileData scriptable object to the TileProbability struct because that makes more sense and is easier to set up.

**Review by DevonHenderson — APPROVED** [review]
## Code Review

> I put the game over trigger on screen because that's where it is in crossy road. But I've moved it anyway.

Oh hadnt realised that. Completely makes sense but had a look over the design doc and it seems like this new implementation is roughly what they want anyway. "If player falls behind the camera, it will be game over."

All the changes to the catchup speed work great, especially the fact you cannot just stay at the top of the screen anymore. Game feels really smooth which is nice

All approved to merge

**Review by LiamMcKenzie — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - The camera catchup looks really good, better than the implementation I had
 - I really like the fence and tree objects, it looks great and works great as a border
 - I agree with what devon mentioned about the gameoverTrigger being better a few units back. I think because our game uses a landscape orientation it makes more sense to be more forgiving.
 - I didn't see this mentioned anywhere, but the target fps code is very helpful.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Lots of great comments
 - Your code can be hard to read at times, but from what I've seen it looks great

_Any repetitive code that could be refactored? (DRY)_  

 - No repetitive code from what I've noticed


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Noticed no bugs


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No performance issues from what i've noticed
 - I think we should keep a list of the placeholder assets we've been using. The fence model works great but ideally we should have a model from the design team.


# Final Comments

 - This pull request is great and should be good to merge.
 - The fence feature and catchup feature maybe could have been moved to separate pull requests

***

**Pull request merged**
