### PR TITLE
Player Movement

### PR DESCRIPTION
**Pull request by LiamMcKenzie**
Linked Issues:
- #3 
- #4

### CODE REVIEW

**Comment by LiamMcKenzie** [comment]
Here is the basic scene setup, I've added simple camera movement.
I still need to add the player movement
prototype

**Comment by JohnathanGlasgow** [comment]
Hey I've had a look at this and it's great. The animation has nice character and the player is maintaining the correct position relative the tiles.
In regards to the issue with the player "disappearing", this is because when then gridchunks are repositioned the list of tile controllers is repopulated so the tiles maintain the correct coordinates. However the player is not updating its coordinates when this happens. So the player doesn't disappear so much as move to a tile offscreen, which also deactivates the player if the tile optimisation is turned on.
A quick, somewhat inelegant solution to this is to fire an event when the RepositionGridChunk method is called is in TileManager. Then listen for this event in PlayerMovement and subtract 14 from the player's x coordinate when it's invoked. I haven't tested this rigorously but it seems to resolve the. issue.

**Review by JohnathanGlasgow — APPROVED** [review]
I've already looked at this and am happy to approve

**Review by DevonHenderson — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the the user’s requirements and properly address the issue?_  

 - Great work on the player movement, everything works great! I really like the buffer on the movement as it feels a lot more fair to the player.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - All good here. Some really helpful comments throughout as well


_Any repetitive code that could be refactored? (DRY)_  

 - None


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Yes, couldnt find any issues 


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No issues


# Final Comments

 - Approved to merge. 
 - In the future we could look at adding WASD to the inputs available as well as this could be more familiar to some users

***

**Pull request merged**
